// components/MeetTheMentors/data.tsx
import {
  Bot,
  Cpu,
  Code2,
  Zap,
  Glasses,
  Plane,
  Users,
  Award,
  GraduationCap,
  Briefcase,
  Drone,
  Box,
} from "lucide-react";
import { Mentor, Stat } from "./types";

export const MENTORS: Mentor[] = [
  {
    id: "pratima ",
    name: "Pratima Thakur",
    role: "Program Architect & Lead Mentor",
    image: "/assets/year-long-course/mentors/image6.png",
    company: "M.Sc Oceanography",
    tags: ["STEM", "Training", "Program Design"],
    linkedinUrl: "https://www.linkedin.com/in/pratimathakur/",
    specialtyIcon: <Glasses size={17} className="text-[#A81B1E]" />,
  },
  {
    id: "shanuli ",
    name: "Shanuli Shinde",
    role: "Robotics Technology Co-Mentor",
    company: "B.Tech Computer Science ",
    tags: ["Robotics", "Technology", "STEM"],
    image: "/assets/year-long-course/mentors/shanuli2.png",
    linkedinUrl: "https://www.linkedin.com/in/shanuli-pravin-shinde-3b5903303",
    specialtyIcon: <Bot size={17} className="text-[#A81B1E]" />,
  },
  {
    id: "mahvish ",
    name: "Mahvish Fatima",
    role: "Electronics & Drones Expert",
    company: "B.Tech Aeronautical Engineering ",
    tags: ["Drones", "Electronics", "Aeronautics"],
    linkedinUrl: "https://www.linkedin.com/in/mahvish-fatima03/",
    image: "/assets/year-long-course/mentors/Mahvish.png",
    specialtyIcon: <Drone size={17} className="text-[#A81B1E]" />,
  },
  {
    id: "Omkar",
    name: "Omkar Shinde",
    role: "Mechanical & Coding Expert",
    company: "B.E Computer Science ",
    tags: ["Mechanical", "Coding", "STEM"],
    linkedinUrl: "https://www.linkedin.com/in/omkarshinde711/",
    image: "/assets/year-long-course/mentors/Omkar.png",
    specialtyIcon: <Code2 size={17} className="text-[#A81B1E]" />,
  },
  {
    id: "anchal ",
    name: "Anchal Mishra",
    role: "Embedded Systems & Coding Expert ",
    company: "BCA",
    image: "/assets/year-long-course/mentors/Anchal.png",

    tags: ["Embedded Systems", "Programming"],
    linkedinUrl: "https://www.linkedin.com/in/anchalmishra1/",
    specialtyIcon: <Cpu size={17} className="text-[#A81B1E]" />,
  },
  {
    id: "nilesh",
    name: "Nilesh Jaiswar",
    role: "Electronics, 3D Printing & Drones Expert",
    image: "/assets/year-long-course/mentors/Nilesh.png",
    company: "B.Tech Mechanical Engineering",
    tags: ["Electronics", "3D Printing", "Drones"],
    linkedinUrl: "https://www.linkedin.com/in/nileshjaiswar/",
    specialtyIcon: <Box size={17} className="text-[#A81B1E]" />,
  },
];
